import fs from "node:fs";
import vm from "node:vm";
import assert from "node:assert/strict";

const source = fs.readFileSync(new URL("./app.js", import.meta.url), "utf8");
const match = source.match(/function roadTax\(powerKw\) \{[\s\S]*?\n\}/);
assert(match, "roadTax function exists");
const context = {};
vm.runInNewContext(`${match[0]}; globalThis.roadTax = roadTax`, context);
assert.equal(context.roadTax(110), 1560);
assert.equal(context.roadTax(218), 2194);
assert.equal(context.roadTax(250), 3398);

const html = fs.readFileSync(new URL("./index.html", import.meta.url), "utf8");
const css = fs.readFileSync(new URL("./styles.css", import.meta.url), "utf8");
assert(html.includes("Dealer interrogation list"));
assert(!html.includes("Add a car"));
assert(!html.includes("AI page importer"));
assert(html.includes("app.js"));
assert(html.includes("Dealer final offers"));
assert(html.includes("Choose the side-by-side"));
assert(html.includes('data-model-preset="tesla"'));
assert(source.includes('id: "tesla-model-3-rwd-110"'));
assert(source.includes('id: "tesla-model-3-premium-110"'));
assert(source.includes('id: "tesla-model-y-110"'));
assert(source.includes('id: "tesla-model-y-premium"'));
assert(source.includes("selectedCarIds"));
assert(source.includes("visibleCars()"));
assert(css.includes("tbody th:not([colspan])"));
assert(css.includes("tr.category-row th { position:relative; z-index:1"));
assert(css.includes(".model-toggle.selected"));
console.log("All calculator checks passed.");
